# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: trivy_image_scan

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main


permissions:
  contents: read

jobs:
    trivy_image_scan_lossprevention:
      permissions:
        contents: read # for actions/checkout to fetch code
        security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
        actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      name: trivy_image_scan
      runs-on: "ubuntu-24.04-8core-300GB"
      steps:
        - name: Checkout code
          uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2
          with:
            ref: main
        - name: Update Sub Module Performance-Tools
          run: make update-submodules
          
        - name: Build and Run Model Downloader image from Dockerfile
          run: |
            echo "running make build-model-downloader"
            make build-model-downloader
            make run-model-downloader

        - name: Build Pipeline Runner image from Dockerfile
          run: |
            echo "running make build-pipeline-runner"
            make build-pipeline-runner

        - name: Run Trivy vulnerability scanner on model-downloader
          uses: aquasecurity/trivy-action@915b19bbe73b92a6cf82a1bc12b087c9a19a5fe2
          with:
            image-ref: 'model-downloader:lp'
            format: 'template'
            template: '@/contrib/sarif.tpl'
            output: 'trivy-results-model-downloader.sarif'
            severity: 'CRITICAL,HIGH'

        - name: Run Trivy vulnerability scanner on pipeline-runner
          uses: aquasecurity/trivy-action@915b19bbe73b92a6cf82a1bc12b087c9a19a5fe2
          with:
            image-ref: 'pipeline-runner:lp'
            format: 'template'
            template: '@/contrib/sarif.tpl'
            output: 'trivy-results-pipeline-runner.sarif'
            severity: 'CRITICAL,HIGH'

        - name: Upload Trivy scan results for model-downloader to GitHub Security tab
          uses: github/codeql-action/upload-sarif@1b549b9259bda1cb5ddde3b41741a82a2d15a841
          with:
            sarif_file: 'trivy-results-model-downloader.sarif'
            category: 'model-downloader'

        - name: Upload Trivy scan results for pipeline-runner to GitHub Security tab
          uses: github/codeql-action/upload-sarif@1b549b9259bda1cb5ddde3b41741a82a2d15a841
          with:
            sarif_file: 'trivy-results-pipeline-runner.sarif'
            category: 'pipeline-runner'



